language: cpp
dist: xenial
compiler:
- clang
os:
- linux
before_install:
- sudo apt-get -y install libfuse-dev libprotobuf-dev protobuf-compiler liblz4-dev
- wget https://www.foundationdb.org/downloads/6.2.10/ubuntu/installers/foundationdb-clients_6.2.10-1_amd64.deb
- sudo dpkg -i foundationdb-clients_6.2.10-1_amd64.deb
script:
- make
